### ISSUE TITLE
Ability to change the new tab page search engine

### ISSUE THREAD

**Issue by glowiak** [angelbruni/Geckium#303] opened 2024-11-09 19:25 UTC
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Gentoo Linux

### What would you like to suggest for Geckium?

I'd like to get rid of Google being on my new tab page.

I have searched the settings and there is no such an option.
Would be grateful if this could be changed.

**Comment by ImSwordQueen** [comment] 2024-11-09 19:26
Duplicate of #267

**Comment by angelbruni** [comment] 2024-11-09 19:26
This is a duplicate of https://github.com/angelbruni/Geckium/issues/267.
The reason on why it's taking so long is because we are still debating on how it's gonna be done.
Chromium had a special page for Bing, but for other engines, it would just get rid of the searchbox entirely.

**Closed** 2024-11-09 19:26 UTC
Labels: Suggestion
