### ISSUE TITLE
Language of dino

### ISSUE THREAD

**Issue by WindowsDefen517** [angelbruni/Geckium#245] opened 2024-10-25 07:40 UTC
### Before reporting your issue

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)
- [X] I deleted the entire "chrome" folder from my Firefox Profile, if there was one, before installing Geckium

### What browser are you running Geckium on?

Mozilla Firefox 115.16.1 ESR

### What Operating System are you running Geckium on?

Windows 7 x64 Ultimate

### Summarise the issue

I saw an issue with the language of the "about:dino" i have download the firefox ESR 115.16.1 in french version and the about:dino is in another language (i don't know what is it). Other things is in french execptly about:dino.
Sorry if i make mistakes i'm french.

### Screenshots

![Capture1](https://github.com/user-attachments/assets/124d1152-8b1d-4d08-af93-7e4e4a03c15f)

### How do you reproduce the bug/inaccuracy?

1. Download Firefox ESR 115.16.1
2. setup geckium
3. go to "about:dino"
4. done

### Expected behaviour or design

if you want to know what is the language of the dino in french : 
![Capture2](https://github.com/user-attachments/assets/344003ea-a085-4061-a672-9f25e26e21e0)

**Comment by angelbruni** [comment] 2024-10-25 13:09
Not a bug, it means that the french translation is not finished, it would be cool if someone could finished it.
I can do those though, and it will be in the next Geckium update https://github.com/angelbruni/Geckium/commit/da8026566f1cf13e56ed4cd82183459f425e8021, thank you for sharing.

By the way, your toolbar layout is wrong, those big gaps before and after the urlbar can be removed if you right click the toolbar -> Customise Toolbar... -> Drag the spaces out.

**Closed by angelbruni** 2024-10-25 13:09 UTC
Labels: Not a bug
